# Publishing Notes

## Setting up GitHub Pages

### gh-pages branch vs. /docs folder

Most of the examples for using Travis use gh-pages though /docs is the newer way to organize things, so not clear which is preferred.  We use gh-pages. Doing so requires a gh-pages branch that is used only for the pages to be published; it does not have the same content as master.  There are various tutorials for how to set up the gh-pages branch; it appears that the best way to do so is to create an orphan branch, as explained [here](https://www.bruttin.com/2017/12/22/github-ghpages-worktree.html).

### Custom domain name

We used Google domains. In [https://domains.google.com/registrar](https://domains.google.com/registrar), click the DNS icon and add the following to Custom resource records:

|NAME|TYPE|TTL|DATA|
|----|----|---|----|
|@|A|1h|185.199.108.153|
|www|cname|1h|@|

* Note that some tutorials list older IP addresses.  Check here for the recommended ones:

[https://help.github.com/articles/troubleshooting-custom-domains/](https://help.github.com/articles/troubleshooting-custom-domains/)

If this is all working, you're ready for the next step.

## Add Travis files to GitHub repo:

Add these files to your repo:

[https://github.com/rstudio/bookdown-demo/blob/master/.travis.yml](https://github.com/rstudio/bookdown-demo/blob/master/.travis.yml)

(No changes)

[https://github.com/rstudio/bookdown-demo/blob/master/_build.sh](https://github.com/rstudio/bookdown-demo/blob/master/_build.sh)

(Remove the last two lines if you're only interested in a GitHub Pages book.)

[https://github.com/rstudio/bookdown-demo/blob/master/_deploy.sh](https://github.com/rstudio/bookdown-demo/blob/master/_deploy.sh)

(The only changes you need to make are to the `git config` lines. You need to use your GitHub email, but the user name can be anything.)

## Adding Travis service

* Create a Travis account on www.travis-ci.org by clicking on "Sign in with GitHub" on the top right.  Click Authorize to allow Travis to have proper access to GitHub.

* Go back to GitHub and create a PAT (personal access token) if you don't have one already.  You can do so [here](https://github.com/settings/tokens). Note that you must save your PAT somewhere because you can't access it once it is created.  Also note that the PAT provides a means to access your GitHub repo through an API, an alternative means to logging in with username/password. (There is an API Token in Travis but this is *not* the one to use.)

* Return to your Travis profile (https://travis-ci.org/profile/[GITHUB username]) and click the button next to the appropriate repo to toggle it on.  Click on Settings next to the button and add your saved GITHUB_PAT under Environmental Variables: set "Name" to "GITHUB_PAT" and "Value" to the value of the token. 

If all goes well, you can sit back, relax, and watch Travis do the work for you.




